### ISSUE TITLE
Does not work with Marathon 1.3+

### ISSUE THREAD

**Issue by nihn** [ContainX/marathon-ldap#5]
Hi,

plugin causes Marathon (v.1.3+) to stop working.
Including Marathon traceback:
```
Sep 21 11:47:45 m1 marathon[20095]: [2016-09-21 11:47:45,204] WARN Error for /v2/events (org.eclipse.jetty.servlet.ServletHandler:qtp416285645-43)
Sep 21 11:47:45 m1 marathon[20095]: java.lang.NoClassDefFoundError: Could not initialize class io.containx.marathon.plugin.auth.type.Action
Sep 21 11:47:45 m1 marathon[20095]: #011at io.containx.marathon.plugin.auth.LDAPAuthorizor.isAuthorized(LDAPAuthorizor.java:27)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.core.event.impl.stream.HttpEventStreamServlet.isAuthorized$1(HttpEventStreamServlet.scala:78)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.core.event.impl.stream.HttpEventStreamServlet.doGet(HttpEventStreamServlet.scala:81)
Sep 21 11:47:45 m1 marathon[20095]: #011at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
Sep 21 11:47:45 m1 marathon[20095]: #011at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:75)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:74)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:75)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:74)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:31)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:35)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep 21 11:47:45 m1 marathon[20095]: #011at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:101)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
Sep 21 11:47:45 m1 marathon[20095]: #011at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.Server.handle(Server.java:517)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
Sep 21 11:47:45 m1 marathon[20095]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
Sep 21 11:47:45 m1 marathon[20095]: #011at java.lang.Thread.run(Thread.java:745)
```

**Comment by gondor** [comment]
Curious, where are you getting 1.3+ from?  Current stable is Marathon 1.1.1?

**Comment by nihn** [comment]
No, Marathon 1.3 was released 9 days ago: https://github.com/mesosphere/marathon/releases/tag/v1.3.0

**Comment by gondor** [comment]
@nihn Ok support has been added and tested.  Download and try v1.3 https://github.com/ContainX/marathon-ldap/releases/tag/1.3

**Comment by nihn** [comment]
@gondor seems to work, thanks!
